=== EvgenyKisel/JD2016-08-22/src/by/it/aborisenok/JD02_07(1)/DTD.dtd
<!ELEMENT ticket (policlinic, visitDate, patient)>
<!ELEMENT policlinic (city, name, doctor)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT doctor (post, name, surname, category, cabinet)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT cabinet (#PCDATA)>
<!ELEMENT visitDate (date, time)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT patient (name, surname, birthDay, address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT birthDay (#PCDATA)>
<!ELEMENT address (city, street, house, room)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT house (#PCDATA)>
<!ELEMENT room (#PCDATA)>

=== EvgenyKisel/JD2016-08-22/src/by/it/aborisenok/JD02_07(1)/XML+DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ticket SYSTEM "DTD.dtd" >
    <ticket>
        <policlinic>
            <city>
                Minsk
            </city>
            <name>
                12's city policlinic
            </name>
            <doctor>
                <post>
                    cardiologist
                </post>
                <name>
                    Martin
                </name>
                <surname>
                    Jonson
                </surname>
                <category>
                    first
                </category>
                <cabinet>
                    434
                </cabinet>
            </doctor>
        </policlinic>
        <visitDate>
            <date>
                2016 12 14
            </date>
            <time>
                13:56
            </time>
        </visitDate>
        <patient>
            <name>
                Tom
            </name>
            <surname>
                Hakins
            </surname>
            <birthDay>
                    1978 09 30
            </birthDay>
            <address>
                <city>
                    Minsk
                </city>
                <street>
                    Nezavisimosti
                </street>
                <house>
                    132
                </house>
                <room>
                    14
                </room>
            </address>
        </patient>
    </ticket>
