<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE airport [
        <!ELEMENT airport (flights)>
        <!ELEMENT flights (flight)+>
        <!ELEMENT flight (company, plane, departureTime, arrivalTime)>
        <!ATTLIST flight
                flightID ID #REQUIRED
                form    CDATA #REQUIRED
                to      CDATA #REQUIRED
                >
        <!ELEMENT company (#PCDATA)>
        <!ELEMENT plane (#PCDATA)>
        <!ELEMENT departureTime (#PCDATA)>
        <!ELEMENT arrivalTime (#PCDATA)>
        ]>
<airport>
    <flights>
        <flight flightID= "OS690" form="MSQ" to="VIE">
            <company>
                Austrian Airlines
            </company>
            <plane>
                Boeing-747
            </plane>
            <departureTime>
                20.08.2016  05:00
            </departureTime>
            <arrivalTime>
                20.08.2016  6:00
            </arrivalTime>
        </flight>
        <flight flightID= "OS727" form="VIE" to="TGD">
            <company>
                Austrian Airlines
            </company>
            <plane>
                Boeing-727
            </plane>
            <departureTime>
                20.08.2016  12:45
            </departureTime>
            <arrivalTime>
                20.08.2016  14:20
            </arrivalTime>
        </flight>
        <flight flightID= "B2736" form="MSQ" to="TBS">
            <company>
                Belavia
            </company>
            <plane>
                Boeing 737-500
            </plane>
            <departureTime>
                13.10.2016  03:45
            </departureTime>
            <arrivalTime>
                13.10.2016  05:45
            </arrivalTime>
        </flight>
    </flights>
</airport>