=== EvgenyKisel/JD2016-08-22/src/by/it/aborisenok/JD02_09/XSD.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://TaskC.JD02_09.aborisenok.it.by/"
        xmlns:tns="http://TaskC.JD02_09.aborisenok.it.by/"
        elementFormDefault="qualified">
    <element name="ticket">
        <complexType>
            <sequence>
                <element name="policlinic" type="tns:policlinic"/>
                <element name="visitDate" type="tns:visitDate"/>
                <element name="patient" type="tns:patient"/>
            </sequence>
        </complexType>
    </element>
        <complexType name="policlinic">
            <sequence>
                <element name="number" type="string"/>
                <element name="doctor" type="tns:doctor"/>
            </sequence>
        </complexType>
        <complexType name="doctor">
            <sequence>
                <element name="post" type="string"/>
                <element name="doctorName" type="string"/>
                <element name="doctorSurname" type="string"/>
                <element name="category" type="string"/>
                <element name="cabinet" type="integer"/>
            </sequence>
        </complexType>
        <complexType name="visitDate">
            <sequence>
                <element name="date" type="date"/>
                <element name="time" type="string"/>
            </sequence>
        </complexType>
        <complexType name="patient">
            <sequence>
                <element name="patientName" type="string"/>
                <element name="patientSurname" type="string"/>
                <element name="birthDay" type="date"/>
                <element name="address" type="tns:address"/>
            </sequence>
        </complexType>
        <complexType name="address">
            <sequence>
                <element name="city" type="string"/>
                <element name="street" type="string"/>
                <element name="house" type="positiveInteger"/>
                <element name="room" type="positiveInteger"/>
            </sequence>
        </complexType>
</schema>

=== EvgenyKisel/JD2016-08-22/src/by/it/aborisenok/JD02_07/XML+XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<ticket
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://JD02_07.aborisenok.it.by/"
        xsi:schemaLocation="http://JD02_07.aborisenok.it.by/ XSD.xsd">
    <policlinic>
        <number>12's city policlinic</number>
        <doctor>
            <post>cardiologist</post>
            <doctorName>Martin</doctorName>
            <doctorSurname>Jonson</doctorSurname>
            <category>first</category>
            <cabinet>434</cabinet>
        </doctor>
    </policlinic>
    <visitDate>
        <date>2016-12-14</date>
        <time>13:56</time>
    </visitDate>
    <patient>
        <patientName>Tom</patientName>
        <patientSurname>Hakins</patientSurname>
        <birthDay>1978-09-30</birthDay>
        <address>
            <city>Minsk</city>
            <street>Nezavisimosti</street>
            <house>132</house>
            <room>14</room>
        </address>
    </patient>
</ticket>
