<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Persons [
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email,Nickname,Password,Ads)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Description,Address,Flat,Flats,Price,Area)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Flat (#PCDATA)>
        <!ELEMENT Flats (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>
        <!ELEMENT Area (#PCDATA)>
        ] >

<Persons>
    <Person>
        <Email>
            dorohov@mail.ru
        </Email>
        <Nickname>
            Dorohov
        </Nickname>
        <Password>
            qwertyuiop
        </Password>
        <Ads>
            <Ad>
                <Description>
                    Теплая уютная квартира в самом центре
                </Description>
                <Address>
                    Минск, ул. Гикало, 12, кв.13
                </Address>
                <Flat>4</Flat>
                <Flats>5</Flats>
                <Price>55555</Price>
                <Area>48.5</Area>

            </Ad>
            <Ad>
                <Description>
                    Уютная квартира в Уручье
                </Description>
                <Address>
                    Минск, ул. Стариновская, 10, кв.113
                </Address>
                <Flat>11</Flat>
                <Flats>16</Flats>
                <Price>85555</Price>
                <Area>58.9</Area>
            </Ad>
        </Ads>
    </Person>
</Persons>