=== EvgenyKisel/JD2016-08-22/src/by/it/opiga/JD_07/orders.dtd
<!ELEMENT orders (order)+>
<!ELEMENT order (client,discription)>
        <!ELEMENT client (FIO, passport, adress,phone)>
        <!ELEMENT FIO (#PCDATA)>
        <!ELEMENT passport (#PCDATA)>
        <!ELEMENT adress (#PCDATA)>
        <!ELEMENT phone (#PCDATA)>
        <!ELEMENT discription (category,arrive,leave,payment)>
        <!ELEMENT category (#PCDATA)>
        <!ELEMENT arrive (#PCDATA)>
        <!ELEMENT leave (#PCDATA)>
        <!ELEMENT payment (#PCDATA)>

=== EvgenyKisel/JD2016-08-22/src/by/it/opiga/JD_07/orders.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE orders SYSTEM "orders.dtd" >
<orders>
    <order>
        <client>
            <FIO>
                Ivanov I.I.
            </FIO>
            <passport>
                MP 25895668
            </passport>
            <adress>
                Gikalo, 14
            </adress>
            <phone>
                80298745898
            </phone>
        </client>
        <discription>
            <category>
                lux
            </category>
            <arrive>
                2016-03-23
            </arrive>
            <leave>
                2016-03-23
            </leave>
            <payment>
                cash
            </payment>
        </discription>
    </order>
</orders>
