=== EvgenyKisel/JD2016-08-22/src/by/it/filimonchik/jd02_07/auto.dtd
<!ELEMENT Dillers (Diller)+>
        <!ELEMENT Diller (Email, Nickname, Password, Ads)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Car_body, Color, Model, Price)>
                <!ELEMENT Car_body (#PCDATA)>
                <!ELEMENT Color (#PCDATA)>
                <!ELEMENT Model (#PCDATA)>
                <!ELEMENT Price (#PCDATA)>

=== EvgenyKisel/JD2016-08-22/src/by/it/filimonchik/jd02_07/auto+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Dillers SYSTEM "auto.dtd" >
<Dillers>
    <Diller>
        <Email>
            test@gmail.com
        </Email>
        <Nickname>
            autodiller
        </Nickname>
        <Password>
            password
        </Password>
        <Ads>

            <Ad>
                <Car_body>
                    Coupe
                </Car_body>
                <Color>
                    Blue
                </Color>
                <Model>
                    Audi
                </Model>
                <Price>
                    5000
                </Price>
            </Ad>

            <Ad>
                <Car_body>
                    Estate
                </Car_body>
                <Color>
                    Red
                </Color>
                <Model>
                    Ferrari
                </Model>
                <Price>
                    10000
                </Price>
            </Ad>

        </Ads>
    </Diller>
</Dillers>
