=== EvgenyKisel/JD2016-08-22/src/by/it/dubatovka/jd02_07/xml_classwork/ad.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://akhmelov.it-academy.by/xml-classwork"
        xmlns:tns="http://akhmelov.it-academy.by/xml-classwork"
        elementFormDefault="qualified">
    <element name="Persons">
        <complexType>
            <sequence>
                <element name="Person"
                         type="tns:Person"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Person">
        <sequence>
            <element name="Email" type="string"/>
            <element name="Nickname" type="string"/>
            <element name="Password" type="string"/>
            <element name="Ads" type="tns:Ads"/>
        </sequence>
    </complexType>
    <complexType name="Ads">
        <sequence>
            <element name="Ad" type="tns:Ad" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Ad">
        <all>
            <element name="Description" type="string"/>
            <element name="Address" type="string"/>
            <element name="Flat" type="positiveInteger"/>
            <element name="Flats" type="positiveInteger"/>
            <element name="Price" type="decimal"/>
            <element name="Square" type="double"/>
        </all>
    </complexType>
</schema>

=== EvgenyKisel/JD2016-08-22/src/by/it/akhmelev/jd02_07/xml_classwork/ad+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Persons xmlns="http://akhmelev.it-academy.by/xml-classwork"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://akhmelev.it-academy.by/xml-classwork ad.xsd">
    <Person>
        <Email>
            dorohov@mail.ru
        </Email>
        <Nickname>
            Dorohov
        </Nickname>
        <Password>
            qwertyuiop
        </Password>
        <Ads>
            <Ad>
                <Description>
                    Теплая уютная квартира в самом центре
                </Description>
                <Addres>
                    Минск, ул. Гикало, 12, кв.13
                </Addres>
                <Flat>4</Flat>
                <Flats>5</Flats>
                <Price>55555</Price>
                <Area>48.5</Area>

            </Ad>
            <Ad>
                <Description>
                    Уютная квартира в Уручье
                </Description>
                <Addres>
                    Минск, ул. Стариновская, 10, кв.113
                </Addres>
                <Flat>11</Flat>
                <Flats>16</Flats>
                <Price>85555</Price>
                <Area>58.9</Area>
            </Ad>
        </Ads>
    </Person>
</Persons>

=== EvgenyKisel/JD2016-08-22/src/by/it/aborisenok/JD02_07/xml_classwork/ad+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Persons xmlns="lesha_borisenok"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="lesha_borisenok ad.xsd">

    <Person>
        <Email>
            dorohov@mail.ru
                </Email>
        <Nickname>
            Dorohov
                </Nickname>
        <Password>
            qwertyuiop
                </Password>
        <Ads>
            <ad>
                <Description>
                    Тёплая уютная квартира в минске
                        </Description>
                <Address>
                    Минск, ул. Гикало, 12, кв.13
                        </Address>
                <Flat>4</Flat>
                <Flats>16</Flats>
                <Price>55555</Price>
                <Area>87.5</Area>
                    </ad>
                </Ads>
            </Person>

    <Person>
        <Email>
            dorgdfgv@mail.ru
        </Email>
        <Nickname>
            Ddfgdv
        </Nickname>
        <Password>
            qwerdfgp
        </Password>
        <Ads>
            <ad>
                <Description>
                    Тёплаяdfgвартира в минске
                </Description>
                <Address>
                    Минскdfgкало, 12, кв.13
                </Address>
                <Flat>6</Flat>
                <Flats>8</Flats>
                <Price>7855</Price>
                <Area>57.5</Area>
            </ad>
        </Ads>
    </Person>
</Persons>
